name: faba_weather_app
description: "FABA International Case Study: Building a Weather Forecast App Using a Public API"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.4
  go_router: ^15.0.0
  shared_preferences: ^2.5.3
  get_it: ^8.0.3
  injectable: ^2.5.0
  fluttertoast: ^8.2.12
  retrofit: ^4.4.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  injectable_generator: ^2.7.0
  retrofit_generator: ^9.1.9
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
